
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  ecommerce_analytics:
    # Applies to all files under models/example/
    staging:
      database: dbt_catalog_cloud
      +materialized: view
      +schema: staging
    intermediate:
      database: dbt_catalog_cloud
      +materialized: view
      +schema: intermediate
    mart:
      +catalog: dbt_catalog_cloud
      +materialized: table
      +schema: marts
      core:
        +catalog: dbt_catalog_cloud
        +materialized: table
      finance:
        +catalog: dbt_catalog_cloud
        +materialized: incremental
        +on_schema_change: "fail"

vars:
  #data range for incremental processing
  start_date: '2023-01-01'
  #custom business logic flags
  include_test_orders: false

snapshots:
  ecommerce_analytics:
    database: dbt_catalog_cloud 
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

seeds:
  database: dbt_catalog_cloud

tests:
  database: dbt_catalog_cloud
flags:
  use_materialization_v2: true
  use_managed_iceberg: true
  require_explicit_package_overrides_for_builtin_materializations: True
  require_model_names_without_spaces: True
  source_freshness_run_project_hooks: True
  restrict_direct_pg_catalog_access: False
  skip_nodes_if_on_run_start_fails: False
  state_modified_compare_more_unrendered_values: False
  require_yaml_configuration_for_mf_time_spines: False
  require_batched_execution_for_custom_microbatch_strategy: False
  require_nested_cumulative_type_params: False
  validate_macro_args: False
  require_all_warnings_handled_by_warn_error: False
  require_generic_test_arguments_property: True
  require_unique_project_resource_names: False
  require_ref_searches_node_package_before_root: False
  require_valid_schema_from_generate_schema_name: False