version: 2

models:
  - name: fct_orders
    description: "Fact table containing completed customer orders"
    columns:
      - name: total_amount
        description: "Total order value"
        tests:
          - positive_values:
              arguments: # Add this
                column_name: total_amount
              severity: warn

      - name: tax_amount
        description: "Tax applied to order"
        tests:
          - positive_values:
              arguments: # Add this
                column_name: tax_amount
              severity: warn

      - name: shipping_amount
        description: "Shipping charges"
        tests:
          - positive_values:
              arguments: # Add this
                column_name: shipping_amount
              severity: warn

      - name: days_since_registration
        tests:
          - positive_values: 
              severity: warn # Config stays at top level
              arguments:     # Add this for the test logic
                column_name: days_since_registration
              